[project]
name = "endlessdb"
version = "0.5.2"
requires-python = ">=3.11"
description = "Endless Database with pyyaml and pymongo"
readme = "README.md"
license = "Apache-2.0"
license-files = ["LICENSE.txt"]

classifiers = [
    "Development Status :: 4 - Beta",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Operating System :: OS Independent",
]

authors = [
  { name="Andrew Berlin", email="a.berlin@33solutions.company" }
]

maintainers = [
  { name="Andrew Berlin", email="a.berlin@33solutions.company" }
]

dependencies = [
  'pymongo >= 4.17.0',
  'pyyaml >= 6.0.3'
]

[project.urls]
repository = "https://github.com/33solutions/endlessdb"
homepage = "https://github.com/33solutions/endlessdb"
issues = "https://github.com/33solutions/endlessdb/issues"
changelog = "https://github.com/33solutions/endlessdb/blob/master/CHANGELOG.md"

[tool.ruff]
target-version = "py311"
line-length = 120
src = ["src", "tests", "samples"]
extend-exclude = [
  "build",
  "dist",
  "*.ipynb",
  "samples/_db",
  "tests/_db",
  "tests/export",
]

[tool.ruff.lint]
select = ["E9", "F", "I"]

[tool.ruff.lint.isort]
known-first-party = ["endlessdb"]

[tool.ruff.format]
line-ending = "lf"

[tool.coverage.run]
branch = true
source = ["endlessdb"]

[tool.coverage.report]
show_missing = true
skip_covered = true
